//! `projects.lock`, from `spec/06-manifest.md` section 6.7.
//!
//! Generated, committed, and holding the hashes. It exists so that a pin move is one reviewable
//! diff with the hash in it, and so that the whole corpus can be checked for integrity from the
//! cache without touching the network.

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::path::Path;

/// The whole lockfile.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Lockfile {
    /// One entry per project, in name order.
    #[serde(default, rename = "project")]
    pub projects: Vec<LockEntry>,
}

impl Lockfile {
    /// Read `projects.lock`. A missing file is an empty lockfile.
    pub fn from_path(path: &Path) -> Result<Self, String> {
        if !path.exists() {
            return Ok(Self::default());
        }
        let text = std::fs::read_to_string(path).map_err(|e| format!("{}: {e}", path.display()))?;
        toml::from_str(&text).map_err(|e| format!("{}: {e}", path.display()))
    }

    /// Write `projects.lock`, sorted by name so that the diff is the pin move and nothing else.
    pub fn write(&self, path: &Path) -> Result<(), String> {
        let mut sorted = self.clone();
        sorted.projects.sort_by(|a, b| a.name.cmp(&b.name));
        let text = toml::to_string_pretty(&sorted).map_err(|e| e.to_string())?;
        let header = "# Generated by `rrc lock`. Do not edit by hand.\n\
                      # A pin move is a diff in this file with the hash in it.\n\n";
        std::fs::write(path, format!("{header}{text}"))
            .map_err(|e| format!("{}: {e}", path.display()))
    }

    /// The entry for a project.
    #[must_use]
    pub fn get(&self, name: &str) -> Option<&LockEntry> {
        self.projects.iter().find(|entry| entry.name == name)
    }

    /// The entries keyed by name, for a caller that wants to look many up.
    #[must_use]
    pub fn by_name(&self) -> BTreeMap<&str, &LockEntry> {
        self.projects
            .iter()
            .map(|entry| (entry.name.as_str(), entry))
            .collect()
    }
}

/// One project's resolved pin.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields, rename_all = "kebab-case")]
pub struct LockEntry {
    /// The project name.
    pub name: String,
    /// The URL the bytes actually came from, which is the primary unless it was dead.
    pub url: String,
    /// The SHA-256 of the archive.
    pub sha256: String,
    /// The size of the archive in bytes, as a second cheap check.
    pub bytes: u64,
    /// The SHA-256 of the licence file inside the extracted tree, so that a licence change
    /// between versions is noticed at the pin move rather than two years later.
    pub licence_sha256: String,
    /// The date the pin was last verified against upstream.
    pub verified: String,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_lockfile_round_trips_and_comes_back_sorted() {
        let lock = Lockfile {
            projects: vec![
                LockEntry {
                    name: "zlib".into(),
                    url: "https://example.invalid/zlib.tar.gz".into(),
                    sha256: "aa".repeat(32),
                    bytes: 10,
                    licence_sha256: "bb".repeat(32),
                    verified: "2026-09-06".into(),
                },
                LockEntry {
                    name: "bzip2".into(),
                    url: "https://example.invalid/bzip2.tar.gz".into(),
                    sha256: "cc".repeat(32),
                    bytes: 20,
                    licence_sha256: "dd".repeat(32),
                    verified: "2026-09-06".into(),
                },
            ],
        };
        let dir = std::env::temp_dir().join("rrc-lockfile-test");
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("projects.lock");
        lock.write(&path).unwrap();
        let read = Lockfile::from_path(&path).unwrap();
        assert_eq!(read.projects.len(), 2);
        assert_eq!(read.projects[0].name, "bzip2");
        assert_eq!(read.get("zlib").unwrap().bytes, 10);
        std::fs::remove_dir_all(&dir).ok();
    }
}
